### ISSUE TITLE
Update scenes / refresh selection for product page demos

### ISSUE THREAD

**Issue by louh** [tangrams/carousel#17]
I'm doing a refresh of demos on project pages on mapzen.com and I've updated (in my branch) the Tangram project page to use the latest SHA commit from carousel: http://precog.mapzen.com/mapzen/blog/lou/fresh-produce/projects/tangram

Couple of observations:
- Tron and Crosshatch are outdated (showing ferry lines, Crosshatch is messier)
- Traditional seems broken (despite loading fine from [here](http://tangrams.github.io/carousel/))

I also asked @bcamper whether we want to swap out any styles with Refill/Cinnabar/Zinc and he also suggested dropping some older scenes and putting in newer ones to keep the page looking fresh. I'll leave this up to you but let me know if I can do anything to help (I have time this week)

**Comment by louh** [comment]
@meetar can I help with any of this?

**Comment by meetar** [comment]
Hi! Nah, I've got it – I've just been clearing out some backlog. I'll bump
this to the top of my list, sorry for the delay!

**Comment by louh** [comment]
whoooooo
